'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';

type Order = { id: string; createdAt: string; total: number; status: string; paymentStatus: string; items: Array<{ id: string; name: string; quantity: number; size: string; price: number; image: string }> };
const statusLabel = (status: string) => status.replace(/_/g, ' ').replace(/\b\w/g, (character) => character.toUpperCase());

export default function OrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch('/api/orders', { cache: 'no-store', credentials: 'include' }).then(async (response) => response.ok ? response.json() : Promise.reject(new Error('Unable to load orders'))).then((data) => setOrders(data.orders ?? [])).catch(() => setOrders([])).finally(() => setLoading(false)); }, []);

  return <main className="min-h-screen bg-[#fff8fa] px-4 py-12 font-sans"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-pink-600">Jannat Elegance</p><h1 className="mt-2 font-serif text-4xl text-maroon-950">My Orders</h1><p className="mt-2 text-sm text-gray-500">Every confirmed purchase, with its invoice and delivery status.</p>{loading ? <p className="py-12 text-sm text-gray-500">Loading your orders…</p> : orders.length === 0 ? <div className="mt-8 rounded-3xl bg-white p-8 text-center shadow-sm"><p className="text-gray-600">You have not placed an order yet.</p><Link href="/shop" className="mt-5 inline-block rounded-full bg-maroon-850 px-6 py-3 text-xs font-bold uppercase tracking-wider text-white">Shop now</Link></div> : <div className="mt-8 space-y-5">{orders.map((order) => <article key={order.id} className="overflow-hidden rounded-3xl border border-maroon-100 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-maroon-50 p-6"><div><p className="font-mono text-xs font-bold text-maroon-950">Order JE{order.id.slice(-8).toUpperCase()}</p><p className="mt-1 text-xs text-gray-500">{new Date(order.createdAt).toLocaleString('en-IN')}</p></div><div className="text-right"><p className="font-bold text-maroon-950">₹{order.total.toLocaleString('en-IN')}</p><p className="mt-1 text-xs font-bold uppercase text-maroon-700">{statusLabel(order.status)}</p></div></div><ul className="divide-y divide-maroon-50 px-6">{order.items.map((item) => <li key={item.id} className="flex items-center gap-4 py-4"><div className="relative h-20 w-16 flex-none overflow-hidden rounded-xl bg-maroon-50"><Image src={item.image || '/images/logo.jpeg'} alt={item.name} fill className="object-cover object-top" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-maroon-950">{item.name}</p><p className="mt-1 text-xs text-gray-500">Size {item.size} · Quantity {item.quantity}</p><p className="mt-1 text-sm font-bold text-maroon-800">₹{(item.price * item.quantity).toLocaleString('en-IN')}</p></div></li>)}</ul><div className="flex justify-end bg-maroon-50/60 px-6 py-4"><Link href={`/orders/${order.id}`} className="rounded-full bg-gradient-to-r from-rose-500 to-pink-600 px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-white shadow-sm transition hover:brightness-110">View order & receipt</Link></div></article>)}</div>}</div></main>;
}
