'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import AdminShell from '@/components/admin/AdminShell';

type Dashboard = { summary: { today: { orders: number; revenue: number }; month: { orders: number; revenue: number }; productCount: number; lowStockCount: number }; lowStock: Array<{ _id: string; name: string; size: string; stock: number }>; recentOrders: Array<{ id: string; customerName: string; total: number; status: string; createdAt: string }> };
const money = (value: number) => `₹${Number(value || 0).toLocaleString('en-IN')}`;
export default function AdminDashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/dashboard', { credentials: 'include' }).then(async (res) => res.ok ? res.json() : Promise.reject(new Error((await res.json()).error))).then((value) => setData(value)).catch(() => setError('Unable to load dashboard data.')); }, []);
  return <AdminShell title="Admin Dashboard">{error && <p className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data ? <p className="p-8 text-center text-sm text-gray-500">Loading dashboard…</p> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'Orders today', value: data.summary.today.orders }, { label: 'Revenue today', value: money(data.summary.today.revenue) }, { label: 'Revenue this month', value: money(data.summary.month.revenue) }, { label: 'Live products', value: data.summary.productCount }].map((card) => <div key={card.label} className="rounded-3xl border border-maroon-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-gray-500">{card.label}</p><p className="mt-3 font-serif text-3xl text-maroon-950">{card.value}</p></div>)}</section><section className="mt-7 grid gap-7 lg:grid-cols-2"><div className="rounded-3xl border border-maroon-100 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl text-maroon-950">Low stock</h2><Link href="/admin/products" className="text-xs font-bold uppercase text-maroon-800">Manage products</Link></div>{data.lowStock.length ? <ul className="mt-4 divide-y divide-maroon-50">{data.lowStock.map((item) => <li key={`${item._id}-${item.size}`} className="flex justify-between py-3 text-sm"><span className="font-semibold text-maroon-950">{item.name} <span className="font-normal text-gray-500">({item.size})</span></span><span className="font-bold text-red-600">{item.stock} left</span></li>)}</ul> : <p className="mt-4 text-sm text-gray-500">No low-stock variants.</p>}</div><div className="rounded-3xl border border-maroon-100 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl text-maroon-950">Recent orders</h2><Link href="/admin/orders" className="text-xs font-bold uppercase text-maroon-800">View orders</Link></div>{data.recentOrders.length ? <ul className="mt-4 divide-y divide-maroon-50">{data.recentOrders.map((order) => <li key={order.id} className="flex items-center justify-between py-3 text-sm"><div><Link href={`/admin/orders/${order.id}`} className="font-semibold text-maroon-950">#{order.id.slice(-8).toUpperCase()}</Link><p className="text-xs text-gray-500">{order.customerName}</p></div><div className="text-right"><p className="font-bold text-maroon-950">{money(order.total)}</p><p className="text-xs capitalize text-maroon-700">{order.status}</p></div></li>)}</ul> : <p className="mt-4 text-sm text-gray-500">No orders yet.</p>}</div></section></>}</AdminShell>;
}
